image: 
  name: registry.gitlab.com/enbuild-staging/hardened-gitlab-runner:latest
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_MESSAGE =~ /.*run-ci.*/i

stages:
    - deploy
    - destroy

deploy-bigbang:
    stage: deploy
    script: ./deploy.sh
    rules:
        # Enabled CI pipeline testing it commit message contains "run-ci"
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_MESSAGE =~ /.*run-ci.*/i

destroy-bigbang:
    stage: destroy
    script: ./destroy.sh
    rules:
        # Enabled CI pipeline testing it commit message contains "run-ci"
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_MESSAGE =~ /.*run-ci.*/i
      when: manual