apiVersion: v1
kind: Secret
metadata:
    name: clusterauditor-values
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:pPGk50PTOmN/CsAYcDy5OMPyxA==,iv:guKsJozT4BmMDv3gTFZs4x+OgevU2FxTMFHHdaT9rdE=,tag:aHcSONe4SKNnIVyy7KRQoA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:986602297069:key/cf300a49-6d7b-4faa-b63b-e8a48b15e97c
          created_at: "2022-02-07T05:45:15Z"
          enc: AQICAHiQphB+Us6VdiZtldhZXtSe6lZw30l4S67lEwW2+/Zm5QH1AhZOt/S+guAcSvBRyPwjAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMtMvKDzUUxjNS27w9AgEQgDtAy/Vr+stT4IuFQgnIkyumDa2SuY40ZbBUy3BSigMdazX1PkDs81+n4XpDSRD4R3Yf6rqugKHQbqwKow==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-07T05:45:15Z"
    mac: ENC[AES256_GCM,data:JT1EVAZaKo6teemKG+giLUZrCPui6vseHCO2MRK2AN9pAixZaezim5JyusV1gvifpcro9q5LfVmLsYrQKRmb0KOkQjE1Qh/Lwmhjwe42pFeB/qAxlS4TpKTjT3Q3d/A1OX1I9DsNiLa8H5QYQpExJVOaxZ0AcnK0gtoBaCZ2xu4=,iv:/oANboF3BfWCSxxyZcbGf2Za85+qNL/Wt0Yjj/ESip0=,tag:xILfU9mgd2CNKmsjJYaslQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.0
