apiVersion: v1
kind: Secret
metadata:
    name: private-registry
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:KfS6J8/tXth2OciSAbkk0CRwmh1FDid4woVEkAtdlHbyBTt8n+6/aOsw07q7EmJpaWwxTDDKYbF8S59m3ycWjuh/1UnPfC2NbzQm141FmMuBo5wknR4f2GKGrFeNmMDei++7yFqzsazny0xxMw3JRxkYeJwPWGPQBcJlGehq2jJC14zyySzT3tv8RJsavw5VIoYzdudOVcZiJgDxrjFJjb4Pvckay6q0lA8ZEmhdAgig3DnelgoFiEeFjcDWM4gG14vPknYZ/VX7gQ2jVti6cJZbDV+cmT7kwh/RF4TIEPSnhHA/x6kHSnQUZtXzGQ+g/Eh6og==,iv:bZ/X/d+CSBI7naicEGkgNiUTEyOQHb2HHYCD3+G2m3Y=,tag:ZFpTq900xDEt0Zz6YsfsCg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:986602297069:key/cf300a49-6d7b-4faa-b63b-e8a48b15e97c
          created_at: "2022-02-07T05:45:07Z"
          enc: AQICAHiQphB+Us6VdiZtldhZXtSe6lZw30l4S67lEwW2+/Zm5QFBqU38+tEnNFk1xWCaJSmMAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMsNYcWT/19rIEjUjxAgEQgDuCzaRZ5Ic/TyRNUPOAtRCFWGY4w2VEM89JbxY0p2dAOLDWVoZP+H7DNBRBJXZSA2mMFBJ+6wLgyIDhdg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-07T05:45:07Z"
    mac: ENC[AES256_GCM,data:Smd2U7nxtWoblJFXc/0+mmGn/BMGMcHePoniX/nPUDUopKOC8v+GF0lkidouo7G7LZ0Zue1onubsVeDz7I2oSF6vTkv/nY8Qaj2O8tJ3p5FJLwV90dQUZ5dBQSPQrhPhnmCufVbXIf3QSTOzvQNoQvKLfXkNoWowFfFaeTF7dlE=,iv:WPTBxBld6OyBMxslS71YoOZmNWI7B6WtDIkAk2ZVAGk=,tag:R6Xk7HbrCuOL+5I2lbxs+w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.0
