apiVersion: v1
kind: Secret
metadata:
    name: repository-credentials
    namespace: bigbang
type: Opaque
data:
    password: ENC[AES256_GCM,data:96hgKjMOoiiGAP1uZx7ddS5zMTSsKrq5MhzT2Q==,iv:AUSmqHirrXp43K/Phd9pfDTMJot97bPvSdMgjScbSkE=,tag:Nu4mZiY/iJt7lO51FhV4KA==,type:str]
    username: ENC[AES256_GCM,data:GWnW+zPiGw2zRNHN10dGGT/7dworpDwa5Xg24i1hRkqEuCZ+,iv:wHpCs2Us9ynVHTiA7EN5TPmrXXB0pT+yFgMT27auxLk=,tag:QxqAsSRYXAd298BcBRw65g==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:986602297069:key/cf300a49-6d7b-4faa-b63b-e8a48b15e97c
          created_at: "2022-02-07T05:45:06Z"
          enc: AQICAHiQphB+Us6VdiZtldhZXtSe6lZw30l4S67lEwW2+/Zm5QEMl1Ra1PyZEvl+5wlJ2KusAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMFtYScOI/EpXs1DngAgEQgDvv2D4dbx8i5AlIFlb7DIRnGa4BqiMYyhC/fqHp36/vONo+uURBpK5F2gk7cnD4eZUhRaa6nHqpOnK8Aw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-07T05:45:06Z"
    mac: ENC[AES256_GCM,data:eJxgDJCb9bl8KDecdlrJLjsi/4Ns6Q1K0FJJN9ILJ1m3pUNjfAmgZtjPXP49pYoTTTQ9b3Eo5TZ5NkXFxtSb8Q41QG6ItxblYa6rkuZxt0YivRtdEICEYxEGcxRSo4z3ekmsdZkBfnXwEJxfALxPiaMZX6J6ZxMwN1Du35w36rg=,iv:/DO03/i0KQae/hzZUvjPDGSXlvuGlHJIvqTr5r1wZTo=,tag:m0TdAIIOGHIIDj46T6MkeA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.0
