apiVersion: v1
kind: Secret
metadata:
    name: repo-values
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:456mMf2sasOcGD/FF+e55mzHQAQnWODmJLzMwjEIpRBqCJYuOM1uJMEW9c98mnUM3fXu/r3Q/m2OHLqs8a+uYyZ/KP11PmffvwmahWg6JDeEbJR9oe2dfkEO2GsmthyhBKKnjeJzT8LVC6kiMzfXFQWDBi+eGS6ibEX2ipyAyT3DTJOLtDH8NijTmLUmPID0Ap2ahqy2cV8da9NuYGM3VYQ6LW7UPribIvvDqwntd47xdHRE1yK4a4wdCBNggnuQCvxyeVPFSiSy1gAFkfzO0uD2Nhil9cxQIUlJsiO9DfHFA0Qqn05yVp8=,iv:O6bU7/vpiRMbfAYY1/WXNLUZYlcCv2ZQrCTmTf1RYno=,tag:NATFbJ1m/viJ2Enn4zUEEw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:986602297069:key/cf300a49-6d7b-4faa-b63b-e8a48b15e97c
          created_at: "2022-02-07T05:45:13Z"
          enc: AQICAHiQphB+Us6VdiZtldhZXtSe6lZw30l4S67lEwW2+/Zm5QGMxR/miwUfMR807a4+E4rHAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMI6F1qDM8jOyGUpjFAgEQgDtsY8kgt66oMJASn++NN9350e/Ah50BE9E7IZsMuREN38TJy20QjL+sOBU0z0/SojYnTgcrx/4REoIdbA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-07T05:45:13Z"
    mac: ENC[AES256_GCM,data:mRl5m6Lpu+GoeVu+QCka99sruBznDvIzgZA1WPwOn1LkqS1pfG7wIpvqlBMih2dBNAZ2sXSo+ALt7V+NYwb2fcdU7gTaPWQHNFTja18t6ML7jEYAQv6PLuosHlUpo4J0VyLx6nR4NYbVFwsv0r4PKupAMqeee5IUuxPjFmezivo=,iv:gkALFO24my5xubjPDDnNYHF3PfMxUm6bcKQI5HbAKig=,tag:C7Zo3O15guOC9ZGs5tEOgQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.0
