apiVersion: v1
kind: Secret
metadata:
    name: twistlock-values
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:rywUvPr8jOHBwCxclqk=,iv:UfteaLWwuNOhFmSIzAo1WQdd2hD96WcuFd+bmz267kk=,tag:DCBK00h3Do/4lURVXR/mdA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:986602297069:key/cf300a49-6d7b-4faa-b63b-e8a48b15e97c
          created_at: "2022-02-07T05:45:18Z"
          enc: AQICAHiQphB+Us6VdiZtldhZXtSe6lZw30l4S67lEwW2+/Zm5QEjHlRJgtPPjsWfFIW5p9SmAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMSyu+dXk3gh7cyd9iAgEQgDtqzre442epGbGHRfPXCC5alxjNJSaA4dc9eMfN8+4OKJYidOqhzjOSiVU/ISAU4eckXuMaMpjFNMy4XA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-07T05:45:18Z"
    mac: ENC[AES256_GCM,data:ebDIxs5LzeEJH+lmbKkMEr3LzgpjQbG1kIeiZU9GF50FQO+v2BAhBi5AL7empavNtIcKKgy/Ijp87EXpRMOZPGUlU30OjvLokjm+qAqez23d84JbFuFlNlapl6no8sXB+46Ig1+xjcyPhzrANUGtJ1r96VZ5nE27sE9hG6Z22NE=,iv:XFax7PzgIXvWigHpqi+8PhsMW2D50xrmle+eqaiXyyE=,tag:TPZhzNGS+Fo9bbuEk/rRCw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.0
