---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: bigbang
spec:
  interval: 1m0s
  url: https://gitlab.com/enbuild-staging/charts/bigbang.git
  ref:
    tag: 1.24.0
  secretRef:
    name: repository-credentials
