---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bigbang
spec:
  chart:
    spec:
      chart: chart
      sourceRef:
        kind: GitRepository
        name: bigbang
        namespace: bigbang
  interval: 2m0s
  values:
    istio:
      git:
        repo: https://gitlab.com/enbuild-staging/charts/istio-controlplane.git
      values:
        hub: registry.gitlab.com/enbuild-staging/container_registry/opensource-istio
        cni:
          image:
            hub: registry.gitlab.com/enbuild-staging/container_registry/opensource-istio
        postInstallHook:
          image: registry.gitlab.com/enbuild-staging/container_registry/big-bang/base:8.4
    istiooperator:
      git:
        repo: https://gitlab.com/enbuild-staging/charts/istio-operator.git
      values:
        hub: registry.gitlab.com/enbuild-staging/container_registry/opensource-istio
    jaeger:
      git:
        repo: https://gitlab.com/enbuild-staging/charts/jaeger.git
      values:
        image:
          repository: registry.gitlab.com/enbuild-staging/container_registry/opensource-jaegertracing/jaeger-operator
        retention:
          image: registry.gitlab.com/enbuild-staging/container_registry/opensource-jaegertracing/jaeger-es-index-cleaner:1.28.0
        jaeger:
          spec:
            allInOne:
              image: registry.gitlab.com/enbuild-staging/container_registry/opensource-jaegertracing/all-in-one:1.28.0
            agent:
              image: registry.gitlab.com/enbuild-staging/container_registry/opensource-jaegertracing/jaeger-agent:1.28.0
            ingestor:
              image: registry.gitlab.com/enbuild-staging/container_registry/opensource-jaegertracing/jaeger-ingestor:1.28.0
            query:
              image: registry.gitlab.com/enbuild-staging/container_registry/opensource-jaegertracing/jaeger-query:1.28.0
            collector:
              image: registry.gitlab.com/enbuild-staging/container_registry/opensource-jaegertracing/jaeger-collector:1.28.0
    kiali:
      git:
        repo: https://gitlab.com/enbuild-staging/charts/kiali.git
      values:
        image:
          repo: registry.gitlab.com/enbuild-staging/container_registry/opensource-kiali/kiali-operator
        cr:
          spec:
            deployment:
              image_name: registry.gitlab.com/enbuild-staging/container_registry/opensource-kiali/kiali
        svcPatchJob:
          image:
            repository: registry.gitlab.com/enbuild-staging/container_registry/big-bang/base
    clusterAuditor:
      git:
        repo: https://gitlab.com/enbuild-staging/charts/cluster-auditor.git
      values:
        image:
          repo: registry.gitlab.com/enbuild-staging/container_registry/cluster-auditor/opa-collector
    gatekeeper:
      git:
        repo: https://gitlab.com/enbuild-staging/charts/gatekeeper.git
      values:
        postInstall:
          image: registry.gitlab.com/enbuild-staging/container_registry/opensource-kubernetes-1.21/kubectl
        postUpgrade:
          cleanupCRD:
            image:
              repository: registry.gitlab.com/enbuild-staging/container_registry/opensource-kubernetes-1.21/kubectl
        image:
          repository: registry.gitlab.com/enbuild-staging/container_registry/opensource-openpolicyagent/gatekeeper
          crdRepository: registry.gitlab.com/enbuild-staging/container_registry/opensource-kubernetes-1.21/kubectl
        violations:
          allowedDockerRegistries:
            enabled: true
            enforcementAction: deny
            kind: K8sAllowedRepos
            name: allowed-docker-registries
            match: {}
            parameters:
              repos:
                - registry.gitlab.com
              excludedResources: []
    kyverno:
      git:
        repo: https://gitlab.com/enbuild-staging/charts/kyverno.git
      values:
        image:
          repository: registry.gitlab.com/enbuild-staging/container_registry/nirmata/kyverno
        initImage:
          repository: registry.gitlab.com/enbuild-staging/container_registry/nirmata/kyvernopre
        testImage:
          repository: registry.gitlab.com/enbuild-staging/container_registry/redhat-ubi/ubi8-minimal
        bbtests:
          scripts:
            image: registry.gitlab.com/enbuild-staging/container_registry/opensource-kubernetes-1.21/kubectl:v1.21.5
    logging:
      git:
        repo: https://gitlab.com/enbuild-staging/charts/elasticsearch-kibana.git
      values:
        kibana:
          image:
            repository: registry.gitlab.com/enbuild-staging/container_registry/elastic-kibana/kibana
        elasticsearch:
          image:
            repository: registry.gitlab.com/enbuild-staging/container_registry/elastic-elasticsearch/elasticsearch
        upgradeJob:
            image:
              repository: registry.gitlab.com/enbuild-staging/container_registry/big-bang/base
    eckoperator:
      git:
        repo: https://gitlab.com/enbuild-staging/charts/eck-operator.git
      values:
        image:
          repository: registry.gitlab.com/enbuild-staging/container_registry/elastic-eck-operator/eck-operator
        upgradeCrds:
          image:
            repository: registry.gitlab.com/enbuild-staging/container_registry/big-bang/base:8.4
    fluentbit:
      git:
        repo: https://gitlab.com/enbuild-staging/charts/fluentbit.git
      values:
        image:
          repository: registry.gitlab.com/enbuild-staging/container_registry/opensource-fluent/fluent-bit
    promtail:
        git:
          repo: https://gitlab.com/enbuild-staging/charts/promtail.git
        values:
          initContainer:
            image:
              registry: registry.gitlab.com/enbuild-staging/container_registry
              repository: big-bang-apps-security-tools-keycloak/busybox
          image:
            registry: registry.gitlab.com
            repository: enbuild-staging/container_registry/opensource-grafana/promtail
    loki:
        git:
          repo: https://gitlab.com/enbuild-staging/charts/loki.git
        values:
          image:
            repository: registry.gitlab.com/enbuild-staging/container_registry/opensource-grafana/grafana-loki
    monitoring:
      git:
        repo: https://gitlab.com/enbuild-staging/charts/monitoring.git
      values:
        cleanUpgrade:
          image: "registry.gitlab.com/enbuild-staging/container_registry/big-bang/base:8.4"
        alertmanager:
          alertmanagerSpec:
            image:
              repository: registry.gitlab.com/enbuild-staging/container_registry/opensource-prometheus/alertmanager
        grafana:
          image:
            repository: registry.gitlab.com/enbuild-staging/container_registry/opensource-grafana/grafana
          testFramework:
            image: registry.gitlab.com/enbuild-staging/container_registry/opensource-bats/bats
          sidecar:
            image:
              repository: registry.gitlab.com/enbuild-staging/container_registry/kiwigrid/k8s-sidecar
          downloadDashboardsImage:
            repository: registry.gitlab.com/enbuild-staging/container_registry/big-bang/base
        kube-state-metrics:
          image:
            repository: registry.gitlab.com/enbuild-staging/container_registry/opensource-kubernetes/kube-state-metrics
        prometheus-node-exporter:
          image:
            repository: registry.gitlab.com/enbuild-staging/container_registry/opensource-prometheus/node-exporter
        prometheusOperator:
          admissionWebhooks:
            patch:
              image:
                repository: registry.gitlab.com/enbuild-staging/container_registry/opensource-ingress-nginx/kube-webhook-certgen
            cleanupProxy:
              image:
                repository: registry.gitlab.com/enbuild-staging/container_registry/big-bang/base
          image:
            repository: registry.gitlab.com/enbuild-staging/container_registry/opensource-prometheus-operator/prometheus-operator
          prometheusConfigReloader:
            image:
              repository: registry.gitlab.com/enbuild-staging/container_registry/opensource-prometheus-operator/prometheus-config-reloader
          thanosImage:
            repository: registry.gitlab.com/enbuild-staging/container_registry/opensource-thanos/thanos
          kubectlImage:
            repository: registry.gitlab.com/enbuild-staging/container_registry/kubernetes-1.21/kubectl:v1.21.1
        prometheus:
          prometheusSpec:
            image:
              repository: registry.gitlab.com/enbuild-staging/container_registry/opensource-prometheus/prometheus
    twistlock:
      git:
        repo: https://gitlab.com/enbuild-staging/charts/twistlock.git
      values:
        console:
          image:
            repository: registry.gitlab.com/enbuild-staging/container_registry/twistlock-console/console
