apiVersion: v1
kind: ConfigMap
metadata:
  name: authservice-values
data:
  values.yaml: |
    addons:
      authservice:
        enabled: false
        git:
          repo: 'https://gitlab.com/enbuild-staging/charts/authservice.git'
          path: ./chart
          tag: 0.4.0-bb.18
        flux: {}
        values: {}
        postRenderers: []
        chains: {}
