apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-values
data:
  values.yaml: |
    jaeger:
      enabled: true
      git:
        repo: 'https://gitlab.com/enbuild-staging/charts/jaeger.git'
        path: ./chart
        tag: 2.27.0-bb.0
      flux:
        install:
          crds: CreateReplace
        upgrade:
          crds: CreateReplace
      ingress:
        gateway: ''
      sso:
        enabled: false
        client_id: ''
        client_secret: ''
      values: {}
      postRenderers: []
