apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali-values
data:
  values.yaml: |
    kiali:
      enabled: true
      git:
        repo: 'https://gitlab.com/enbuild-staging/charts/kiali.git'
        path: ./chart
        tag: 1.44.0-bb.1
      flux: {}
      ingress:
        gateway: ''
      sso:
        enabled: false
        client_id: ''
        client_secret: ''
      values: {}
      postRenderers: []
