apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-values
data:
  values.yaml: |
    monitoring:
      enabled: true
      git:
        repo: 'https://gitlab.com/enbuild-staging/charts/monitoring.git'
        path: ./chart
        tag: 23.1.6-bb.1
      flux:
        install:
          crds: CreateReplace
        upgrade:
          crds: CreateReplace
      ingress:
        gateway: ''
      sso:
        enabled: false
        prometheus:
          client_id: ''
          client_secret: ''
        alertmanager:
          client_id: ''
          client_secret: ''
        grafana:
          client_id: ''
          client_secret: ''
          scopes: ''
          allow_sign_up: 'true'
          role_attribute_path: Viewer
      values: {}
      postRenderers: []
