apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bigbang
resources:
  - ../../base
  - bigbang-deploy.yaml
patchesStrategicMerge:
  - patch-bigbang.yaml
  - reclaimpolicy-patch.yaml
