---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bigbang
spec:
  valuesFrom:
    - name: repo-values
      kind: ConfigMap
    - name: istio-values
      kind: ConfigMap
    - name: istiooperator-values
      kind: ConfigMap
    - name: jaeger-values
      kind: ConfigMap
    - name: kiali-values
      kind: ConfigMap
    - name: clusterauditor-values
      kind: ConfigMap
    - name: gatekeeper-values
      kind: ConfigMap
    - name: logging-values
      kind: ConfigMap
    - name: eckoperator-values
      kind: ConfigMap
    - name: fluentbit-values
      kind: ConfigMap
    - name: monitoring-values
      kind: ConfigMap
    - name: twistlock-values
      kind: ConfigMap
    # - name: kyverno-values
    #   kind: ConfigMap
    # - name: promtail-values
    #   kind: ConfigMap
    # - name: loki-values
    #   kind: ConfigMap
    - name: repo-values
      kind: Secret
    - name: istio-values
      kind: Secret
    - name: istiooperator-values
      kind: Secret
    - name: jaeger-values
      kind: Secret
    - name: kiali-values
      kind: Secret
    - name: clusterauditor-values
      kind: Secret
    - name: gatekeeper-values
      kind: Secret
    - name: logging-values
      kind: Secret
    - name: eckoperator-values
      kind: Secret
    - name: fluentbit-values
      kind: Secret
    - name: monitoring-values
      kind: Secret
    - name: twistlock-values
      kind: Secret
    # - name: promtail-values
    #   kind: Secret
    # - name: loki-values
    #   kind: Secret
    # - name: kyverno-values
    #   kind: Secret