# -- Toggle deployment of Logging (EFK).
enabled: true
git:
  repo: https://gitlab.com/enbuild-staging/charts/elasticsearch-kibana.git
  path: "./chart"
  tag: "0.4.0-bb.0"

# -- Flux reconciliation overrides specifically for the Logging (EFK) Package
flux:
  timeout: 20m

# Redirect the package ingress to a specific Istio Gateway (listed in `istio.gateways`).  The default is "public".
ingress:
  gateway: ""

sso:
  # -- Toggle OIDC SSO for Kibana/Elasticsearch on and off.
  # Enabling this option will auto-create any required secrets.
  enabled: false

  # -- Elasticsearch/Kibana OIDC client ID
  client_id: ""

  # -- Elasticsearch/Kibana OIDC client secret
  client_secret: ""

license:
  # -- Toggle trial license installation of elasticsearch.  Note that enterprise (non trial) is required for SSO to work.
  trial: false

  # -- Elasticsearch license in json format seen here: https://repo1.dso.mil/platform-one/big-bang/apps/core/elasticsearch-kibana#enterprise-license
  keyJSON: ""

# -- Values to passthrough to the elasticsearch-kibana chart: https://gitlab.com/enbuild-staging/charts/elasticsearch-kibana.git
values: {}

# -- Post Renderers.  See docs/postrenders.md
postRenderers: []